# Generated by Django 3.0.7 on 2020-06-28 09:14

from django.db import migrations, models
import django.db.models.deletion
import image_hosting.images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to=image_hosting.images.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ImageThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_type', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to=image_hosting.images.models.image_upload_path)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='images.Image')),
            ],
        ),
    ]
